### ISSUE TITLE
loader for es5 modules

### ISSUE THREAD

**Issue by vijaywm** [sJhonny-e/angular-starter#1]
I am building on existing an existing project in ES5 code written with closures. I've moved the code into your project template and will use ES6 modules going forward. Is it possible to import all the old through some loader in the webpack config, so I don't need to import all the previous closure code individually ?

**Comment by sJhonny-e** [comment]
hmm, interesting question.  
when you say 'closures', I guess you mean [IIFEs](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression)?  

In any case, it seems that webpack has [a few suggestions](https://webpack.github.io/docs/shimming-modules.html), or you can go the same way as [this guy](http://stackoverflow.com/q/29421409) on SO.

Hope this helps; let me know if you have any other questions :)

**Comment by vijaywm** [comment]
I created a module that imports all the old IFFE js and included this module as a dependency in app.js, this worked. 

However, the SO link looks better, I'll give that a try.

```
// iffeloader.js

import './theme.module'
import './theme.config'
import './theme.constants'
import './theme.configProvider'
import './theme.service'
import './theme.run'

const module = angular.module('iffeloader', [])
.name;
export default module;

```
