### ISSUE TITLE
include bower components in samples

### ISSUE THREAD

**Issue by vijaywm** [sJhonny-e/angular-starter#2]
Can you throw in a few bower packages in the sample.. useful when porting existing projects that use bower components to webpack

**Comment by sJhonny-e** [comment]
Although it may be useful in some cases, I don't want to over-complicate by introducing dependencies which aren't strictly necessary;  
One of the advantages (in my opinion) of this setup is that it uses plain NPM for everything, so I'd rather keep it that way

**Comment by vijaywm** [comment]
fair enough. Thanks.
